spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password: $2a$10$1G3EImK46GA6C9BOA9gJcuIitF3YaXKwjIazh/IxkairzXplXP1rC
  jackson:
    serialization:
      indent_output: true
  datasource:
    username: dev
    password: diarydev
    url: jdbc:mysql://localhost:3306/flightdiary
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    sessionStatEnable: true
    profileEnable: true
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    validationQuery: select 1
    maxOpenPreparedStatements: 20
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  thymeleaf:
    mode: HTML5
    cache: false
logging:
  level:
    root: info
    org.ramer.diary: debug
    org.ramer.diary.repository: debug
    org.springframework.boot.autoconfigure: info
    org.springframework.sercurity: debug
    jdbc.resultset: info
    jdbc.audit: info
    jdbc.sqlonly: info
    jdbc.sqltiming: debug
    jdbc.connection: info
server:
  session:
    tracking-modes: COOKIE
  port: 80
diary:
  encrypt.strength: 10
  topic:
    page:
      size: 36
  topPeople:
    page:
      size: 6
  personal:
    topic:
      page:
        size: 3
  qiniu:
    access: FYfmtmhBMAGZyxZothLB50hgn18an3T1PKLa4nVz
    secret: YeX5dBtF1Gq2tA-35AosS22O9FalPglj5rRChPDR
    bucketName: diary
  tags:
    xml:
      position: /xml/tags.xml
  page:
    scroll: true
